# Generated by Django 3.1.5 on 2021-01-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210123_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='errCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='errTimestamp',
            field=models.BigIntegerField(null=True),
        ),
    ]
