# Generated by Django 3.1.5 on 2021-01-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_websiteinfo_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='errCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cache',
            name='errTimestamp',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
