version: "3"
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./init:/docker-entrypoint-initdb.d/"
    environment:
      - MYSQL_ROOT_PASSWORD=decision-test
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=tic-test
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
  backend:
    image: backend:latest
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=decision-test
      - MYSQL_USERNAME=root
      - MYSQL_DATABASE=tic-test
      - ENV=production
    ports:
      - 8000:8000
    command:
      - /bin/bash
      - -c
      - |
        cd /usr/src/app
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000
  frontend:
    image: frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - db
      - backend
    ports:
      - 80:80