# Generated by Django 3.1.5 on 2021-01-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VXPage',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=30)),
                ('avatar', models.CharField(max_length=128)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('context', models.TextField()),
            ],
            options={
                'db_table': 'tic_vxpage',
            },
        ),
    ]
