# Generated by Django 3.1.5 on 2021-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vxpage',
            name='datetime',
        ),
        migrations.AddField(
            model_name='vxpage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
